services:
  frontend:
    build:
      context: UI
      dockerfile: Dockerfile
    depends_on: 
      - redis
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  redis:
    image: redis:latest
    hostname: redis
    restart: always
    expose: 
      - 6379